### ISSUE TITLE
the linux_libnfc-nci_examples don't include Write function 

### ISSUE THREAD

**Issue by niguang1** [NXPNFCLinux/linux_libnfc-nci_examples#1]
The README.md sys that "This example demonstrates simple tag reader/writer mode "raw exchanges" using the linux_libnfc-nci library." but the code didn't realized it actually.

**Comment by jgeslin** [comment]
In this statement, "reader/writer mode" means capability to read and write into a tag.
The example shows indeed how to send any command to a card in "Raw" using `nfcTag_transceive `API.
Then, by looking to the card related specification you can found what dedicate card command have to be used to perform a write operation. 
For instance, for a MIFARE Ultralight card, the 4 bytes block write command is "A2". E.g. you can write "0x11223344" to block number 8 with such parameter value:

> unsigned char WriteCmd[] = {0xA2U, 0x08, 0x11, 0x22, 0x33, 0x44};
