### ISSUE TITLE
How can i set a specific UID to PN7150 when i run in HCE mode?

### ISSUE THREAD

**Issue by niguang1** [NXPNFCLinux/linux_libnfc-nci_examples#2]
when i run the card-emulation_example ,my reader device shows that the uid of  pn7150 is "040302010400",but how can i set a specific UID to PN7150?
       what document i can reference？

**Comment by jgeslin** [comment]
I assume you are referring to type A card emulation mode.
This is defined in NFC Forum NCI specification, UID is set via CORE-SET_CONFIG command to define value of  NCI parameter LA_NFCID1 (id 0x33).

You can change linux_libnfc-nci library default value updating NXP_CORE_CONF parameter within libnfc-nxp-pn548.conf configuration file:

```
NXP_CORE_CONF={ 20, 02, 2B, 0D,
    28, 01, 00,
    21, 01, 00,
    30, 01, 08,
    31, 01, 03,
    33, 04, 04, 03, 02, 01,
    54, 01, 06,
    50, 01, 02,
    5B, 01, 00,
    60, 01, 0E,
    80, 01, 01,
    81, 01, 01,
    82, 01, 0E,
    18, 01, 01
}
```

In line `33, 04, 04, 03, 02, 01,`:
- "33" is the parameter id for LA_NFCID1
- "04" is the UID length
- "04 03 02 01" is the UID value you can change to set the value you expect

If you wish to change the UID size, pay attention to reflect it in the UID length field but also in the  command payload length (third bytes of the NXP_CORE_CONF parameter, "2B" by default).

For instance, if you want to use 7 bytes UID length "07 06 05 04 02 03 01":
```
NXP_CORE_CONF={ 20, 02, 2E, 0D,
    28, 01, 00,
    21, 01, 00,
    30, 01, 08,
    31, 01, 03,
    33, 07, 07, 06, 05, 04, 03, 02, 01,
    54, 01, 06,
    50, 01, 02,
    5B, 01, 00,
    60, 01, 0E,
    80, 01, 01,
    81, 01, 01,
    82, 01, 0E,
    18, 01, 01
}
```

Or for RID (randomly generated for each session):
```
NXP_CORE_CONF={ 20, 02, 2B, 0D,
    28, 01, 00,
    21, 01, 00,
    30, 01, 08,
    31, 01, 03,
    33, 04, 08, 00, 00, 00,
    54, 01, 06,
    50, 01, 02,
    5B, 01, 00,
    60, 01, 0E,
    80, 01, 01,
    81, 01, 01,
    82, 01, 0E,
    18, 01, 01
}
```

Hope this help.

**Comment by niguang1** [comment]
I set the data as you say and It works correctly! But now, I have a new puzzle.
My application need to emulate different card at different moment,Is there anyway to change the config by software(except modify configuration file)?

**Comment by jgeslin** [comment]
The linux_libnfc-nci library doesn't offer API for dynamically changing the card-emulation UID. Indeed the UID value is stored in PN7150 internal EEPROM memory, updating it dynamically would lead to EEPROM memory write cycle overrun.

**Comment by niguang1** [comment]
I modify the configuration file and restart my application,my reader display a new UID.But if i don't restart my application,the UID don't changed too.Can you provide me a interface to modefy the UID online？
And what should i write to the file if i want to emulate another type of card? Is there a description about the data of the configuration file except the AN11697 chapter 4.4？

**Comment by jgeslin** [comment]
Please find attached a patch exposing an API to do so.
[patch_SetNciParameter.txt](https://github.com/NXPNFCLinux/linux_libnfc-nci_examples/files/3824973/patch_SetNciParameter.txt)

Then you can set LA_NFCID1 parameter as is:
```
unsigned char UID[] = {0x04, 0x03, 0x02, 0x01};
nfcManager_setConfig(0x33, sizeof(UID), UID);
```

**Comment by jgeslin** [comment]
Regarding emulating other types, please refer to https://github.com/NXPNFCLinux/linux_libnfc-nci_examples/tree/master/card-emulation_example.

**Comment by niguang1** [comment]
Works well,Thanks!
